Fix build error
error: Bad source: /home/abuild/rpmbuild/SOURCES/0007-Fix-build-error-if-compiler-is-clang.patch: No such file or directorym
Signed-off-by: Chenxi Mao <chenxi.mao@suse.com>
(cherry picked from commit fd6702ef6ffaf3a6cdf11b78e9a6292f6fece0e5)